add support for sending and receiving raw binary data using []byte channels
beatrichartz/martini-sockets pull request #10
Opened 2017-06-09 02:03 UTC by michael2008

This is mainly for supporting customized serialization method like Protobuf and reduce message size in performance-critical scenarios.

2017-06-10 08:57 UTC, beatrichartz requested changes
Thanks for this, looking good overall - nice testing, and a valuable addition to this library. There are some minor consistency issues, and the commits should be squashed.

I think the main thing to change is how we name the new interface. I know the motivation for this comes from protobufs, so you are thinking about binary messages. However, byte slices are not restricted to a particular serialization format, so I think we should rename this to something like `sockets.ByteSliceMessage` or similar. What are your thoughts?

2017-06-10 08:57 UTC, beatrichartz commented on sockets.go
> +// default options mentioned in the documentation of the Options object.
This documentation needs updating so it reflects that this is about `[]byte` channels

2017-06-10 08:57 UTC, beatrichartz commented on README.md
> +
This does not need to argue its usefulness that much, i.e. you could remove:

> The lower-level Gorilla Websocket supports sending raw bytes, and the high-level Martini middleware should also support it. The binary message channel is quite useful, where you can directly send your data using customized serialization methods like Protobuf. Message size is crucial in some use cases.

2017-06-10 08:57 UTC, beatrichartz commented on sockets.go
> +type BinaryConnection struct {
This should be renamed to e.g. `ByteSliceConnection`. `BinaryConnection` suggests a `[]bool`, but we have a `[]byte`

2017-06-10 08:57 UTC, beatrichartz commented on sockets.go
> +	// Receiver is the []byte channel used for receiving binary data from the client.
Similarly here this is not specific to receiving binary data. I know the motivation for this is protobufs, but technically this is agnostic to what the byte slice represents.

2017-06-10 08:57 UTC, beatrichartz commented on sockets.go
> +func BinaryMessages(options ...*Options) martini.Handler {
As per the other comments, this should be something like `ByteSliceMessages`

2017-06-10 08:57 UTC, beatrichartz commented on sockets.go
> +
This should be removed

2017-06-10 08:57 UTC, beatrichartz commented on sockets_test.go
> +	recvBinaryPath  string = "/binary/receiver"
As per the other comments, this should be something like `"/byteslice/receiver"`

2017-06-10 08:57 UTC, beatrichartz commented on sockets_test.go
> +	sendBinarysPath string = "/binary/sender"
same here

2017-06-10 08:57 UTC, beatrichartz commented on sockets_test.go
> +	sendBinaryDone     bool
This section needs renaming for byteslices as well

2017-06-10 08:57 UTC, beatrichartz commented on sockets_test.go
> +
same for the tests.

2017-06-11 02:34 UTC, michael2008 commented
ByteSliceConnection is good and suitable for golang naming convention. Also, I will revise the docs to reflect these changes.

2017-06-11 15:56 UTC, beatrichartz approved these changes

2017-06-11 15:57 UTC, merged